export const mockProducts: Product[] = [
  {
    id: "1",
    productImg: "https://picsum.photos/seed/product-1/400/400",
    productName: "Audífonos Inalámbricos Pro X",
    productUrl: "https://example.com/products/audifonos-pro-x",
    rating: 4.7,
    product_external_id: "ext-1001",
  },
  {
    id: "2",
    productImg: "https://picsum.photos/seed/product-2/400/400",
    productName: "Smartwatch Active Fit 2",
    productUrl: "https://example.com/products/smartwatch-active-fit-2",
    rating: 4.3,
    product_external_id: "ext-1002",
  },
  {
    id: "3",
    productImg: "https://picsum.photos/seed/product-3/400/400",
    productName: "Mochila Urbana Antirrobo",
    productUrl: "https://example.com/products/mochila-urbana-antirrobo",
    rating: 4.9,
    product_external_id: "ext-1003",
  },
  {
    id: "4",
    productImg: "https://picsum.photos/seed/product-4/400/400",
    productName: "Lámpara LED Minimalista",
    productUrl: "https://example.com/products/lampara-led-minimalista",
    rating: 4.1,
    product_external_id: "ext-1004",
  },
  {
    id: "5",
    productImg: "https://picsum.photos/seed/product-5/400/400",
    productName: "Teclado Mecánico RGB TKL",
    productUrl: "https://example.com/products/teclado-mecanico-rgb-tkl",
    rating: 4.8,
    product_external_id: "ext-1005",
  },
  {
    id: "6",
    productImg: "https://picsum.photos/seed/product-6/400/400",
    productName: "Silla Ergonómica ProDesk",
    productUrl: "https://example.com/products/silla-ergonomica-prodesk",
    rating: 4.5,
    product_external_id: "ext-1006",
  },
];